In [6]:
import numpy as np
import pandas as pd

# Numpy

In [22]:
#1. 다음 보기와 같이 0이상 10미만의 3x3 모양의 정수 난수를 생성
# 각 행의 첫 번째 값으로 정렬하시오. (5점)
a = np.round(np.random.randint(0,10,(3,3)))
print(a)
print(a[a[:,0].argsort()])
# a.sort(axis=0)
# print(a)


[[5 1 7]
 [2 8 2]
 [8 9 8]]
[[2 8 2]
 [5 1 7]
 [8 9 8]]


In [23]:
# 2. 8x8 모양의 정수 0으로 채워진 행렬을 만들고
# 인덱싱과 슬라이싱을 이용하여 체크보드 패턴을만드시오. (10점)
a = np.zeros((8,8), dtype=int)
a[::2, 1::2] = 1
a[1::2, ::2] = 1
a



array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [24]:
# 3. [0,1) 사이의 값을 갖는 크기 10의 랜덤 벡터를 만들고
# 최대값을 0으로 바꾸는 코드를 만드시오. (5점)
a = np.random.rand(10)
a = np.sort(a)[::-1]

a[np.argmax(a)] = 0
print(a)

# 다른방법
r= np.random.rand(10)
r[r.max() == r] = 0
print(r)


[0.         0.81472218 0.68020774 0.6555207  0.52412752 0.29907352
 0.25587433 0.25205799 0.24409754 0.20395769]
[0.33629168 0.61233237 0.41553834 0.23775307 0.         0.38386899
 0.02721374 0.61972468 0.11208017 0.55806378]


# Pandas
# 월드컵 출전선수 골 기록 데이터 분석 (30점)

In [25]:
import pandas as pd
df = pd.read_csv('worldcupgoals.csv')
print(df.shape)
df.head()

(1295, 4)


Player  Goals                Years  Country
0  Miroslav Klose     16  2002-2006-2010-2014  Germany
1         Ronaldo     15       1998-2002-2006   Brazil
2     Gerd Muller     14            1970-1974  Germany
3   Just Fontaine     13                 1958   France
4            Pele     12  1958-1962-1966-1970   Brazil

In [28]:
#1 주어진 전체 기간의 각 나라별 골 득점수 상위 5개 국가와
# 그 득점수를 출력하시오
grouped = df.groupby('Country')['Goals'].sum().sort_values(ascending=False)


# grouped = df.groupby('Country')[['Goals']].sum().sort_values('Goals',ascending=False)
# print(grouped.unique())
print(grouped.head(5))



Country
Brazil       228
Germany      226
Argentina    135
Italy        123
France       115
Name: Goals, dtype: int64


In [29]:
# 2 주어진 전체기간동안 골득점을 한 선수가 가장 많은 나라
# 상위 5개 국가와 그 선수 숫자를 출력하시오.
grouped = df.groupby('Country')['Player'].count().sort_values(ascending=False)
print(grouped.unique())
print(df['Player'].unique())
print(grouped.head(5))

# grouped = df.groupby('Country').count().sort_values('Player',ascending=False).head()

[81 78 60 59 58 48 46 42 39 38 37 36 30 28 24 23 22 20 19 18 17 16 14 13
 12 11 10  9  8  7  6  5  4  3  2  1]
['Miroslav Klose' 'Ronaldo' 'Gerd Muller' ... 'Aleksandar Tirnanic'
 'Djordje Vujadinovic' 'Branko Zebec']
Country
Brazil       81
Germany      78
Italy        60
Argentina    59
France       58
Name: Player, dtype: int64


In [44]:
df[df['Years'] == '0'].count()

Player     45
Goals      45
Years      45
Country    45
dtype: int64

In [46]:
# 3. Years 컬럼은 년도 -년도 형식으로 구성 되어있고,
# 각 년도는 4자리 숫자이다.
# 
# 
# 2006-2010
# 2010
# 0
#  years = 2002-2006-2010-2014
# years.split('-') = [2002,2006,2010,2014]
# year = 2002
# year = 2006
# year = 2010
# year = 2014
count = 0
for years in df['Years']:
  for year in years.split('-'):
    if len(year) != 4:
      count += 1
print(count)


45


In [62]:
# 4 3번 문제에서 발생한 예외 케이스(년도 표기가 4자리 숫자가 아닌 경우)
# 를 제외한 새로운 데이터 프레임을 생성하고 전체 데이터 행의 숫자를 출력하시오.
def chaeckYearFormat(years):
  for year in years.split('-'):
    if len(year) != 4:
      return False
  return True

df['year_check'] =  df['Years'].apply(lambda x: chaeckYearFormat(x))
check = df['year_check'] == False
print(check.sum())

df_new = df[df['year_check']]
df_new.shape

45


(1250, 5)

In [66]:
# 5. 월드컵 출전횟수를 나타내는 ‘LenCup’ 컬럼을 추가하고 4회 출전한 선수의 숫자를 구하시오.
import warnings
warnings.filterwarnings(action='ignore')
df_new['LenCup'] = [len(years.split('-')) for years in df_new['Years']]
len(df_new[df_new['LenCup'] == 4])
# df['LenCup'] =  df[df['Player'].unique() == df['Player']].count()
# df

16

In [67]:
# 유고슬라비아 국가의 월드컵 출전횟수가 2회인 선수들의 숫자
len(df_new[df_new['Country']== 'Yugoslavia'][df_new['LenCup'] == 2])

7

In [69]:
# 2002년도에 출전한 전체 선수 수를 구하시오.
len(df_new[df_new['Years'].str.contains('2002')])

156

In [70]:
# 11 월드컵 출전횟수가 1회 뿐인 선수들 중에서 가장 많은 득점을 올렸던 선수는 누구이며 몇 골을 넣었는지 구하시오.
df_new[df_new['LenCup'] ==1].sort_values('Goals',ascending=False).head(10)
# [['Player','Goals']]

Player  Goals Years    Country  year_check  LenCup
3         Just Fontaine     13  1958     France        True       1
6         Sandor Kocsis     11  1954    Hungary        True       1
13               Ademir      9  1950     Brazil        True       1
21              Eusebio      9  1966   Portugal        True       1
24    Guillermo Stabile      8  1930  Argentina        True       1
39         Erich Probst      6  1954    Austria        True       1
44      James Rodriguez      6  2014   Colombia        True       1
46           Harry Kane      6  2018    England        True       1
50          Max Morlock      6  1954    Germany        True       1
53  Salvatore Schillaci      6  1990      Italy        True       1

# 전 세계 행복도 지수 데이터 분석 (30점)

In [71]:
df = pd.read_csv('happiness.csv')
df.shape


(312, 10)

In [72]:
df.head()

행복랭킹          나라명     점수  상대GDP  사회적지원  행복기대치  선택의 자유도    관대함  부패에 대한인식   
0     1      Finland  7.769  1.340  1.587  0.986    0.596  0.153     0.393  \
1     2      Denmark  7.600  1.383  1.573  0.996    0.592  0.252     0.410   
2     3       Norway  7.554  1.488  1.582  1.028    0.603  0.271     0.341   
3     4      Iceland  7.494  1.380  1.624  1.026    0.591  0.354     0.118   
4     5  Netherlands  7.488  1.396  1.522  0.999    0.557  0.322     0.298   

     년도  
0  2019  
1  2019  
2  2019  
3  2019  
4  2019

In [73]:
df['년도'].unique()

array([2019, 2018])

In [77]:
#각 연도별 행복랭킹 10위안에 드는 나라의 행복점수의 평균을 구하시오.
grouped =  df.groupby('년도')[['행복랭킹']].mean().head(10)
grouped


행복랭킹
년도        
2018  78.5
2019  78.5

In [75]:
df[df['행복랭킹'] <= 10].groupby('년도')['점수'].mean()

년도
2018    7.4442
2019    7.4559
Name: 점수, dtype: float64

In [ ]:
# 각 연도의 행복랭킹 50위 이내의 나라들의 각각의 행복점수 평균을 데이터프레임으로 표시하시오.
# mean()
# groupby()
# pd.DataFrame()

In [76]:
# 각 년도별 하위 행복점수의 하위 5개 국가의 평균 행복점수를 구하시오.
grouped =  df.groupby('나라명')['점수'].mean().sort_values(axis=0, ascending=True).head(5)
grouped

나라명
South Sudan                 3.0535
Central African Republic    3.0830
Tanzania                    3.2670
Burundi                     3.3400
Yemen                       3.3675
Name: 점수, dtype: float64

In [293]:
# 2019년 데이터를 추출하고 해당 데이터의 상대 GDP 평균 이상의 나라들과 평균 이하의 나라들의 행복점수 평균을
# 각각 구하고 그 차이 값을 출력하시오
df = df[df['년도'] == 2019]
df_up = df[df['상대GDP'] >= df['상대GDP'].mean()]
df_down = df[df['상대GDP'] <= df['상대GDP'].mean()]

df = df_up - df_down
df


행복랭킹  나라명  점수  상대GDP  사회적지원  행복기대치  선택의 자유도  관대함  부패에 대한인식  년도
2    NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
5    NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
13   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
15   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
20   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
28   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
33   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN
50   NaN  NaN NaN    NaN    NaN    NaN      NaN  NaN       NaN NaN

In [ ]:
# 각 년도의 부패에 대한인식을 내림차순 정렬했을 때
# 상위 20개 국가의 부패에 대한인식의 평균을 구하시오.
# mean() , groupby(), sort_values(), head(20)

In [ ]:
# 2018년도 행복랭킹 50위 이내에 포함됐다가 2019년 50위 밖으로 밀려난 국가의 숫자를 구하시오.


In [ ]:
# 2018년,2019년 모두 기록이 있는 나라들 중 년도별 행복점수가 가장 증가한 나라와 그 증가 수치는?

# 유튜브 데이터 분석 (20점)

In [97]:
data = pd.read_csv('youtube_rank.csv')
data.info()
data.shape
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   title       1000 non-null   object
 1   category    1000 non-null   object
 2   subscriber  1000 non-null   object
 3   view        1000 non-null   object
 4   video       1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB


title    category subscriber       view   video
0                    BLACKPINK  [음악/댄스/가수]      5140만  128억5130만    319개
1               Big Hit Labels  [음악/댄스/가수]      4550만  120억8966만    433개
2                    BANGTANTV  [음악/댄스/가수]      3870만   54억7598만  1,319개
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]      2650만  110억5288만    223개
4                       SMTOWN  [음악/댄스/가수]      2450만  180억7532만  3,583개

In [98]:
# 컬럼의 이름을 다음과 같이 변경하시오
# ◼title : 채널명, category : 카테고리, subscriber : 구독자수, view : 조회수, video : 영상개수
data.rename(columns = {'title':'채널명',
              'category':'카테고리',
              'subscriber':'구독자수',
              'view':'조회수',
              'video':'영상개수'}, inplace=True)
data.head(5)

채널명        카테고리   구독자수        조회수    영상개수
0                    BLACKPINK  [음악/댄스/가수]  5140만  128억5130만    319개
1               Big Hit Labels  [음악/댄스/가수]  4550만  120억8966만    433개
2                    BANGTANTV  [음악/댄스/가수]  3870만   54억7598만  1,319개
3  Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  2650만  110억5288만    223개
4                       SMTOWN  [음악/댄스/가수]  2450만  180억7532만  3,583개

In [99]:
# ‘구독자수’ 컬럼과 ‘조회수’ 컬럼의 타입을 정수형(int64)로 변경하시오 (‘억’,’만’ 한글을 삭제 후 숫자로 변경)
data.info()
data['구독자수'] = data['구독자수'].str.replace('만',"0000").astype(np.int64)
data['조회수'] = data['조회수'].str.replace('억',"")
data['조회수'] = data['조회수'].str.replace('만',"0000").astype(np.int64)
# data['구독자수'] = data['구독자수'].str.replace('만',"0000").astype(np.int64)
# data['조회수'] = data['조회수'].replace(['억','만'],['','0000']).astype(np.int64)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   채널명     1000 non-null   object
 1   카테고리    1000 non-null   object
 2   구독자수    1000 non-null   object
 3   조회수     1000 non-null   object
 4   영상개수    1000 non-null   object
dtypes: object(5)
memory usage: 39.2+ KB


In [100]:
data.info()
data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   채널명     1000 non-null   object
 1   카테고리    1000 non-null   object
 2   구독자수    1000 non-null   int64 
 3   조회수     1000 non-null   int64 
 4   영상개수    1000 non-null   object
dtypes: int64(2), object(3)
memory usage: 39.2+ KB


채널명        카테고리      구독자수          조회수     영상개수
0                      BLACKPINK  [음악/댄스/가수]  51400000  12851300000     319개
1                 Big Hit Labels  [음악/댄스/가수]  45500000  12089660000     433개
2                      BANGTANTV  [음악/댄스/가수]  38700000   5475980000   1,319개
3    Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000     223개
4                         SMTOWN  [음악/댄스/가수]  24500000  18075320000   3,583개
..                           ...         ...       ...          ...      ...
995                Ranking World       [미분류]    400000    127520000     503개
996                         급식걸즈    [취미/라이프]    400000    239010000     226개
997                          OCN     [TV/방송]    400000    345830000  10,071개
998                Bravo jamoasi       [미분류]    400000     61930000      25개
999                  덕출 : DCTVGO     [TV/방송]    400000     82490000     202개

[1000 rows x 5 columns]

In [101]:
# ‘영상개수’ 컬럼의 ‘,’와 ‘개’문자를 제거하고 정수형(int32)로 변경하시오.
data['영상개수'] = data['영상개수'].str.replace('개',"")

In [102]:
data['영상개수'] = data['영상개수'].str.replace(',',"").astype(np.int32)

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   채널명     1000 non-null   object
 1   카테고리    1000 non-null   object
 2   구독자수    1000 non-null   int64 
 3   조회수     1000 non-null   int64 
 4   영상개수    1000 non-null   int32 
dtypes: int32(1), int64(2), object(2)
memory usage: 35.3+ KB


In [119]:
# 4 인기 채널 확인하기
# ◼’구독자수’와 ‘조회수’가 많은 5개의 채널을 각각 출력하시오.
# data['구독자수'].sort_values(ascending=False).head()
# data['조회수'].sort_values(ascending=False).head()

data.sort_values(['구독자수','조회수'],ascending=False).head()[['채널명','구독자수','조회수']]
asdf = data.set_index('채널명')
asdf


카테고리      구독자수          조회수   영상개수
채널명                                                                  
BLACKPINK                    [음악/댄스/가수]  51400000  12851300000    319
Big Hit Labels               [음악/댄스/가수]  45500000  12089660000    433
BANGTANTV                    [음악/댄스/가수]  38700000   5475980000   1319
Boram Tube Vlog [보람튜브 브이로그]    [키즈/어린이]  26500000  11052880000    223
SMTOWN                       [음악/댄스/가수]  24500000  18075320000   3583
...                                 ...       ...          ...    ...
Ranking World                     [미분류]    400000    127520000    503
급식걸즈                           [취미/라이프]    400000    239010000    226
OCN                             [TV/방송]    400000    345830000  10071
Bravo jamoasi                     [미분류]    400000     61930000     25
덕출 : DCTVGO                     [TV/방송]    400000     82490000    202

[1000 rows x 4 columns]

In [122]:
# 5 ‘카테고리’가 [음악/댄스/가수]인 채널의 ‘구독자수’ 상위 5개를 출력하시오.
data[data['카테고리'] == '[음악/댄스/가수]']['구독자수'].head(5)

0    51400000
1    45500000
2    38700000
4    24500000
5    22300000
Name: 구독자수, dtype: int64

In [125]:
# 6 ‘카테고리가’ [TV/방송]이거나 [게임]인 채널의 개수를 출력하시오.
# data[np.logical_or(data['카테고리'] == '[TV/방송]',data['카테고리'] ==  '[게임]' )].count()
data[data['카테고리'].isin(['[TV/방송]','[게임]'])].count()

채널명     262
카테고리    262
구독자수    262
조회수     262
영상개수    262
dtype: int64

In [127]:
# 7 ‘채널명’에 ‘KBS’가 포함된 채널 명을 출력하시오.
data[data['채널명'].str.contains('KBS')]

채널명        카테고리      구독자수          조회수    영상개수
12                  KBS World     [TV/방송]  14300000  10158060000   46830
46                   KBS Kpop     [TV/방송]   5260000   3411260000   24389
76              KBS Entertain     [TV/방송]   3930000   5340910000   91783
101                 KBS Drama     [TV/방송]   3040000   3538510000  105922
290                  KBS 한국방송     [TV/방송]   1220000   1128510000   25993
292         KBS Drama Classic  [뉴스/정치/사회]   1210000   1084400000    8783
308           KBS HUMAN: 뭉클티비     [TV/방송]   1170000    495680000    1593
389                  KBS News  [뉴스/정치/사회]    960000   1017410000  145515
457                KBS CoolFM     [TV/방송]    840000    429520000    6981
716                     KBS N     [TV/방송]    560000    747830000   12470
777                  KBS KONG  [뉴스/정치/사회]    520000    191610000    6639
991  KBS Documentary [KBS 다큐]  [뉴스/정치/사회]    400000    245060000   48383
992                    KBS 교양  [뉴스/정치/사회]    400000    297960000   64694

In [129]:
# 8 ‘카테고리’별 ‘구독자수’, ‘조회수’, ‘영상개수’의 평균을 출력하시오.
grouped = data.groupby('카테고리')[['구독자수','조회수','영상개수']].mean()
grouped


구독자수           조회수          영상개수
카테고리                                                 
[BJ/인물/연예인]  1.274412e+06  4.101549e+08    837.735294
[IT/기술/컴퓨터]  8.062500e+05  1.766100e+08   1200.125000
[TV/방송]      1.219876e+06  7.184834e+08   9025.130435
[게임]         7.435644e+05  4.542535e+08   2527.009901
[교육/강의]      8.513043e+05  1.772183e+08    837.913043
[국내/해외/여행]   6.260000e+05  1.866240e+08    830.200000
[뉴스/정치/사회]   1.226964e+06  1.199936e+09  42048.089286
[미분류]        1.429500e+06  4.090340e+08    778.050000
[스포츠/운동]     9.325000e+05  2.791892e+08   3954.916667
[애완/반려동물]    1.161000e+06  4.213170e+08    786.250000
[영화/만화/애니]   8.527273e+05  3.185870e+08    770.181818
[음식/요리/레시피]  1.612045e+06  4.073819e+08    830.022727
[음악/댄스/가수]   3.195200e+06  1.091668e+09   1382.051429
[자동차]        4.900000e+05  1.856150e+08    670.000000
[주식/경제/부동산]  6.260000e+05  6.800000e+07   1026.400000
[취미/라이프]     9.745000e+05  2.043118e+08    359.325000
[취미]         5.600000e+05  1.061500e+08    237.000000
[키즈/어린이]     2.729158e+06  1.281384e+09   1069.157895
[패션/미용]      8.238596e+05  1.043774e+08    313.157895
[해외]         1.595000e+06  8.382533e+08   5043.500000
[회사/오피셜]     2.202500e+06  4.966125e+08   2084.250000