# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [1]:
import numpy as np

data = np.loadtxt('height_weight.txt', delimiter=",",dtype=float)
print(data)

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]


In [7]:
weight = data[1]
print(weight)
squared_height_m = (data[0] / 100) **2
print(squared_height_m)

bmi = weight / squared_height_m
print(bmi)

np.set_printoptions(suppress=True, precision=2)

print('BMI 23이상인 사람들의 BMI')
print(bmi[bmi >= 23])


[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]
[3.069504 3.250809 3.0625   2.862864 3.429904 3.5344   3.154176 3.175524
 3.1329   3.2041  ]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]
BMI 23이상인 사람들의 BMI
[27.07 25.86 24.21 23.14 23.62 25.59]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기 <data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float, skiprows=1)>
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [72]:
import numpy as np

data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=float, skiprows=1, encoding='cp949')

# 성별 연령그룹 수축기혈압(120미만) 확장기혈압(80미만) 공복혈당(126>=당뇨, 나머지 정상) 
# 진료여부 체질량지수

# 전체 레코드 수와 상위 5개 데이터 확인
# TODO 분석초기단계때 데이터 파악을먼저 해야됨
print(data[:3])
#  데이터 모양 확인
print(f'레코드 수{data.shape[0]:,}개')

[[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]]
레코드 수1,000,000개


In [78]:
#  여성과 남성의 데이터 수 확인
# boolean 인덱싱
male = data[:,0] == 1
female = data[:,0] == 2
# print(f'남성데이터수:{len(data[data[:,0] == 1]):,}개')
print(sum(male))
print(sum(female))


510227
489773


In [80]:

# 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인


subset = data[:,:4]
print("남성 수축기혈압의 평균:",np.mean(subset[subset[:,0]==1][:,2]))
print("여성 수축기혈압의 평균:",np.mean(subset[subset[:,0]==2][:,2]))
print("남성 이완기혈압의 평균:",np.mean(subset[subset[:,0]==1][:,3]))
print("여성 이완기혈압의 평균:",np.mean(subset[subset[:,0]==2][:,3]))
male_sbp_mean = np.mean(data[data[:,0]==1][:,2])
print(male_sbp_mean)



남성 수축기혈압의 평균: nan
여성 수축기혈압의 평균: nan
남성 이완기혈압의 평균: nan
여성 이완기혈압의 평균: nan
nan


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/numpy/core/_methods.py:194: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret / rcount


In [ ]:
#  정상 혈압 남자 및 여자 수 확인
nbp_masking = np.logical_and(data[:,2] < 120,data[:,3] < 80)
nbp_data = data[nbp_masking]
print(f'정상혈압 남자 수: {sum(nbp_data[:,0]==1)}')
print(f'정상혈압 여자 수: {sum(nbp_data[:,0]==2)}')

#  당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수
diabetes = data[data[:,4] >= 126]
print(f'당뇨병 질환 환자의 평균 BMI: {np.mean(diabetes[:,6]):.2f}')

print(data[:,data[:,:6]])

# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [90]:
# - 'Seattle2014.csv' 파일 내용 읽기
data = np.loadtxt('Seattle2014.csv',delimiter=',',dtype=object,skiprows=1)
print(data[:2])



[['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140101' '0' '0' '0' '72' '33' '12' '340' '310' '36' '40' '-9999'
  '-9999' '-9999' '-9999']
 ['GHCND:USW00024233' 'SEATTLE TACOMA INTERNATIONAL AIRPORT WA US'
  '20140102' '41' '0' '0' '106' '61' '32' '190' '200' '94' '116' '-9999'
  '-9999' '-9999' '-9999']]


In [108]:
# - 강수량('PRCP')이 많은 날 상위 10일 확인
prcp = data[:,3].astype(int)
top_10 = np.sort(prcp)[::-1][:10]
print(top_10)
subset = np.sort(data[:,3].astype(int))[::-1][:10]
print(subset)


[467 343 333 323 320 277 264 254 221 216]
[467 343 333 323 320 277 264 254 221 216]


In [110]:
#펜싱 인덱싱
prcp = data[:,[2,3]].astype(int)
prcp = prcp[prcp[:,1].argsort()][::-1][:10]

print(prcp)


[[20140305      467]
 [20141128      343]
 [20140503      333]
 [20140308      323]
 [20141022      320]
 [20140316      277]
 [20140216      264]
 [20141030      254]
 [20140328      221]
 [20140129      216]]


In [117]:
# - 1월 강수량만 출력
prcp = data[:,[2,3]]
prcp_month = np.array([[data[4:6],prcp] for data, prcp in prcp])
jan_prcp = prcp_month[prcp_month[:,0] == '01'][:,1].astype(int)
print(jan_prcp)


[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


In [118]:
# - 1월에 내린 강수량의 합, 평균강수량 확인
print(np.sum(jan_prcp))
print(np.mean(jan_prcp))

940
30.322580645161292


In [119]:
# - 1년동안 강수량이 40미만으로 내린 날이 몇일인가?
prcp = data[:,3].astype(int)
under_40 =prcp[prcp < 40]
print(len(under_40))

277


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [7]:
import numpy as np
# - 'ratings.dat' 파일 내용 읽기
data = np.loadtxt('ratings.dat',delimiter=":", dtype=int)
# - 상위 10개 데이터 출력하기
print(data[:5])
# - 데이터 정보 확인(크기, 차원)
data.shape

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]


(1000209, 4)

In [46]:
# - 전체 데이터 평점 구하기
avg_score = data[:,2].mean()
print(avg_score)
# - 사용자 아이디 1인 데이터 출력하기
user_id = data[data[:,0] == 1][:5]
print(user_id)
# - 사용자 아이디 1인 사람의 평점 평균 구하기
print(np.mean(user_id[:,2]))




3.581564453029317
[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]]
4.0


In [50]:
# - 각 사용자별 평균평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
user_ids = np.unique(data[:,0])
print(len(user_ids),"명")
user_mean_rating =[ [id,np.mean(data[data[:,0] == id][:,2])] for id in user_ids ]
for id , avg_rating in user_mean_rating[:10]:
    print(f'{id} : {avg_rating:.2f}점')


# for id in user_ids:
#     data_user = data[data[:,0] == id,:]
#     value = data_user[:,2].mean()
#     user_mean_rating.append([id,value])
# print("결과",user_mean_rating[:3])

6040 명
1 : 4.19점
2 : 3.71점
3 : 3.90점
4 : 4.19점
5 : 3.15점
6 : 3.90점
7 : 4.32점
8 : 3.88점
9 : 3.74점
10 : 4.11점


In [52]:
# - 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기
user_mean_rating = np.array(user_mean_rating)
user_mean_rating[:10]
print(f'평균 평점이 4점 이상인 유저 수:{sum(user_mean_rating[:,1] >= 4)}')

# for user_id in unique_user_id:
#     data_user = data[data[:,0] == user_id,:]
#     value = np.mean(data_user[:,2])
#     user_mean_value.append([user_id,value])
# print("결과",user_mean_value[:3])


평균 평점이 4점 이상인 유저 수:1544
