[문제-1] 길이가 10인 0-벡터를 만드세요.

In [7]:
import numpy as np

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [19]:

a = np.arange(10)
a[:] = 0
a[5:-4] = 1
print(a)

[0 0 0 0 0 1 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [22]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

[문제-4] 위 벡터의 순서를 바꾸세요.

In [29]:
a = np.arange(10,50)[::-1]
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [30]:
a = np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [44]:
a = np.array([1, 2, 0, 0, 4, 0])
a = a[a != 0]  
print(a)

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [47]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [51]:
a = np.random.rand(3,3)
print(a)

[[0.73506601 0.56770558 0.08625577]
 [0.616351   0.03155331 0.83358505]
 [0.44570479 0.20973301 0.18129233]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [74]:
a = np.round(np.random.randint(0,10,(3,3)))
print(a)
print("최댓값:",np.round(np.amax(a)))
print("최솟값:",np.round(np.amin(a)))

[[9 0 7]
 [5 4 7]
 [2 8 3]]
최댓값: 9
최솟값: 0


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [83]:
a = np.round(np.random.randint(0,10,(3,3)))
print(a)
print("0",np.mean(a, axis=0))
print("1",np.mean(a, axis=1))

[[1 0 0]
 [6 0 1]
 [8 1 2]]
0 [5.         0.33333333 1.        ]
1 [0.33333333 2.33333333 3.66666667]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [86]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

array([10, 37, 38, 10, 22, 47, 17, 35, 49])

[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [88]:
np.random.randint(10,51,9).reshape(3,3)

array([[39, 33, 12],
       [28, 22, 30],
       [20, 36, 10]])

 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [90]:
a = np.random.randint(10,51,9).reshape(3,3)
print(a)
np.sum(a,axis=0)

[[23 13 25]
 [35 39 29]
 [17 41 39]]


array([75, 93, 93])

[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [91]:
np.random.randint(10,51,9).reshape(3,3)
print(a)
np.amax(a,axis=1)

[[23 13 25]
 [35 39 29]
 [17 41 39]]


array([25, 39, 41])

[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [92]:
a = np.random.randint(10,51,9).reshape(3,3)
print(a)
np.mean(a)

[[40 45 31]
 [21 25 26]
 [41 41 33]]


33.666666666666664

 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [114]:
a = np.random.randint(1,10,6).reshape(2,3)
print(a)

[[3 1 9]
 [2 6 5]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [113]:
b = np.random.randint(10,20,6).reshape(3,2)
print(a)

[[3 7 4]
 [7 9 5]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [128]:
a = np.random.randint(1,10,6).reshape(3,2)
print(a)
b = np.random.randint(10,20,6).reshape(2,3)
print(b)

print(a@b)


[[6 5]
 [5 5]
 [5 5]]
[[13 17 16]
 [17 15 15]]
[[163 177 171]
 [150 160 155]
 [150 160 155]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [134]:
(a@b).T

array([[163, 150, 150],
       [177, 160, 160],
       [171, 155, 155]])

[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [136]:
a = np.random.randint(1,47,6)
print(a)

[23 40 28  7 24 11]
