# 붓꽃 분류

## 패키지 로딩

In [2]:
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

## 데이터 로딩 및 분할

In [3]:
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0, stratify=y)

## 모델 생성

In [4]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

## 모델 평가

In [5]:
y_hat = model.predict(X_test)
print(f'Accuracy: {accuracy_score(y_test, y_hat):.3f}')

Accuracy: 0.967


In [6]:
con_mat = confusion_matrix(y_test, y_hat)
print(con_mat)

[[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]


# 2. 독버섯 분류

In [42]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score,roc_auc_score
import pandas as pd
import numpy as np

In [43]:
mushroom_df = pd.read_csv('mushrooms.csv')
mushroom_df.head()

type cap_shape cap_surface cap_color bruises     odor gill_attachment   
0  poisonous    convex      smooth     brown     yes  pungent            free  \
1     edible    convex      smooth    yellow     yes   almond            free   
2     edible      bell      smooth     white     yes    anise            free   
3  poisonous    convex       scaly     white     yes  pungent            free   
4     edible    convex      smooth      gray      no     none            free   

  gill_spacing gill_size gill_color  ... stalk_surface_below_ring   
0        close    narrow      black  ...                   smooth  \
1        close     broad      black  ...                   smooth   
2        close     broad      brown  ...                   smooth   
3        close    narrow      brown  ...                   smooth   
4      crowded     broad      black  ...                   smooth   

  stalk_color_above_ring stalk_color_below_ring veil_type veil_color   
0                  white                  white   partial      white  \
1                  white                  white   partial      white   
2                  white                  white   partial      white   
3                  white                  white   partial      white   
4                  white                  white   partial      white   

  ring_number   ring_type spore_print_color population  habitat  
0         one     pendant             black  scattered    urban  
1         one     pendant             brown   numerous  grasses  
2         one     pendant             brown   numerous  meadows  
3         one     pendant             black  scattered    urban  
4         one  evanescent             brown   abundant  grasses  

[5 rows x 23 columns]

### 2.3 데이터 인코딩 및 분할

In [44]:
def labeling(col):
  map_data = {v:i for i, v in enumerate(np.sort(col.unique()))}
  return map_data

mushroom_df = mushroom_df.apply(lambda col : col.map(labeling(col)))
mushroom_df.head()

type  cap_shape  cap_surface  cap_color  bruises  odor  gill_attachment   
0     1          2            3          0        1     7                1  \
1     0          2            3          9        1     0                1   
2     0          0            3          8        1     1                1   
3     1          2            2          8        1     7                1   
4     0          2            3          3        0     6                1   

   gill_spacing  gill_size  gill_color  ...  stalk_surface_below_ring   
0             0          1           0  ...                         3  \
1             0          0           0  ...                         3   
2             0          0           1  ...                         3   
3             0          1           1  ...                         3   
4             1          0           0  ...                         3   

   stalk_color_above_ring  stalk_color_below_ring  veil_type  veil_color   
0                       7                       7          0           2  \
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring_number  ring_type  spore_print_color  population  habitat  
0            1          4                  0           3        4  
1            1          4                  1           2        0  
2            1          4                  1           2        2  
3            1          4                  0           3        4  
4            1          0                  1           0        0  

[5 rows x 23 columns]

In [45]:
# 버섯df.drop('type',axis=1)
X = mushroom_df.iloc[:,1:]
y = mushroom_df['type']

In [46]:
# 학습 데이터와 평가 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.8, random_state=10,stratify=y)

In [47]:
# 모델 생성 및 학습
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

### 2.5 모델 평가

In [48]:
# 예측
y_hat = model.predict(X_test)
cf_mat = confusion_matrix(y_test,y_hat)
print(cf_mat)

[[2985  382]
 [ 714 2419]]


In [21]:
# 평가
accuracy = accuracy_score(y_test, y_hat)

print(f'정확도:', accuracy)
print(f'정밀도:', accuracy)
print(f'정밀도:', accuracy)

정확도: 0.955701394585726


In [ ]:
X = mushroom_df,d[d[['']]]